use_frameworks!

target 'EFCountingLabel_Example' do
  pod 'EFCountingLabel', :path => '../'

  target 'EFCountingLabel_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.1'
        end
    end
end